import type { Metadata, Viewport } from "next";
import localFont from 'next/font/local'
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1
}

const myfonts = localFont({
  src: [
    {
      path: '../../public/fonts/woff/IRANSansX-Thin.woff',
      weight: '100',
      style: 'normal'
    },
    {
      path: '../../public/fonts/woff/IRANSansX-Regular.woff',
      weight: '300',
      style: 'normal'
    },
    {
      path: '../../public/fonts/woff/IRANSansX-Medium.woff',
      weight: '500',
      style: 'normal'
    },
    {
      path: '../../public/fonts/woff/IRANSansX-Bold.woff',
      weight: 'bold',
      style: 'normal'
    },
    {
      path: '../../public/fonts/woff2/IRANSansX-Thin.woff2',
      weight: '100',
      style: 'normal'
    },
    {
      path: '../../public/fonts/woff2/IRANSansX-Regular.woff2',
      weight: '300',
      style: 'normal'
    },
    {
      path: '../../public/fonts/woff2/IRANSansX-Medium.woff2',
      weight: '500',
      style: 'normal'
    },
    {
      path: '../../public/fonts/woff2/IRANSansX-Bold.woff2',
      weight: 'bold',
      style: 'normal'
    },
    // from here
    {
      path: '../../public/fonts/numerals/Woff/IRANSansXFaNum-Thin.woff',
      weight: '100',
      style: 'normal'
    },
    {
      path: '../../public/fonts/numerals/Woff/IRANSansXFaNum-Regular.woff',
      weight: '300',
      style: 'normal'
    },
    {
      path: '../../public/fonts/numerals/Woff/IRANSansXFaNum-Medium.woff',
      weight: '500',
      style: 'normal'
    },
    {
      path: '../../public/fonts/numerals/Woff/IRANSansXFaNum-Bold.woff',
      weight: 'bold',
      style: 'normal'
    },
    {
      path: '../../public/fonts/numerals/Woff2/IRANSansXFaNum-Thin.woff2',
      weight: '100',
      style: 'normal'
    },
    {
      path: '../../public/fonts/numerals/Woff2/IRANSansXFaNum-Regular.woff2',
      weight: '300',
      style: 'normal'
    },
    {
      path: '../../public/fonts/numerals/Woff2/IRANSansXFaNum-Medium.woff2',
      weight: '500',
      style: 'normal'
    },
    {
      path: '../../public/fonts/numerals/Woff2/IRANSansXFaNum-Bold.woff2',
      weight: 'bold',
      style: 'normal'
    },
  ]
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className={myfonts.className}>
      <body>{children}</body>
    </html>
  );
}
